name: Deploy WordPress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Remove Existing WordPress Files
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
          "sudo rm -rf /var/www/html/wordpress/*"

      - name: Sync Files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/var/www/html/wordpress"
          strip_components: 1

      - name: Set Correct Ownership and Permissions
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
          "sudo chown -R www-data:www-data /var/www/html/wordpress && \
           sudo find /var/www/html/wordpress -type d -exec chmod 755 {} \; && \
           sudo find /var/www/html/wordpress -type f -exec chmod 644 {} \;"
